### ISSUE TITLE
Docker: Attempted to load class "MakerBundle" from namespace "Symfony\Bundle\MakerBundle". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by michaelmiklis** [jimmycleuren/loxone-weather-service#207]
After spinning up the container using your docker-compose.yml sample file and pointing DNS "weather.loxone.com" to my container, I receive the following error when I access http://weather.loxone.com:6066/forecast/

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/34162433/154941762-b175059d-77da-42af-a092-5b8fcabd5f55.png">

I have no clue on symfony - cloud you point me in the right direction?

**Comment by markdegrootnl** [comment]
Add `APP_ENV=prod` to the environment in your docker-compose file

**Comment by michaelmiklis** [comment]
Thank you @markdegrootnl that fixed the issue but brought me to another.
I also added redis image and the redis_url to the environment but seems not working:

URL: http://weather.loxone.com:6066/forecast/?user=loxone_504F11223344&coord=13.8408,48.6051&asl=20&format=1
`app.INFO: Saving location for loxone_xxxxxxxxxxxxx: lat=48.6051, lon=13.8408, asl=20 [] []
app.INFO: Updating cache [] []`

Manually updating weather data inside the container with:
`/usr/local/bin/php /app/bin/console app:update-weather >> /var/log/cron.log 2>&1`

Generates the following log entries:
app.INFO: Updating cache [] []
[OK] Weather successfully retrieved 

any further hints how to get it working?

**Comment by markdegrootnl** [comment]
What output are you getting when you open the url in the browser?

**Comment by michaelmiklis** [comment]
An empty page

**Comment by michaelmiklis** [comment]
Looked almost the same, except REDIS_URL. I hat "redis://localhost:6379" change that to "redis://redis" and now it is working. Thank you a lot!

Documentation should definitely updated.

**Comment by markdegrootnl** [comment]
Great, happy to help.
