### ISSUE TITLE
Symfony MakerBundle error

### ISSUE THREAD

**Issue by gck303** [jimmycleuren/loxone-weather-service#326]
I am getting a Symfony error when I run it. 

It is running in Docker. The DNS is all adjusted and I have tested with a ping from within the docker. 

Thanks, George

![2024-01-04 17_16_13-Attempted to load class _MakerBundle_ from namespace _Symfony_Bundle_MakerBundle](https://github.com/jimmycleuren/loxone-weather-service/assets/30334661/3197e1a0-84ba-45cc-9234-19513802f36f)

**Comment by gck303** [comment]
I tried adding an ENV parameter to the docker. 

It seemed to help.

**Comment by jimmycleuren** [comment]
If you do a composer install with the --no-dev parameter, you should indeed use prod as the APP_ENV.
