### ISSUE TITLE
Broken after updating config to 15.1.8.5

### ISSUE THREAD

**Issue by TimWuyts** [jimmycleuren/loxone-weather-service#328]
<img width="1679" alt="Scherm­afbeelding 2024-08-19 om 13 57 44" src="https://github.com/user-attachments/assets/55921416-6917-44a3-bd9f-227eee8f3aa5">

After updating my Loxone config to 15.1.8.5 the weather service seems to be broken. I'm assuming the data structure/endpoint has been changed which is causing the weather overview to show wrong values (see screenshot). 

Do you have any idea where I could look into the data structure in order to create a PR to fix this issue?

**Comment by jimmycleuren** [comment]
#329 seems to fix it for me, can you update to the latest version and try again ?
